/**
 * POST /api/send-email
 *
 * Body:
 *   {
 *     to: "client@x.com" | comma-separated,
 *     cc?: string,
 *     company: "GSK",
 *     articles: Article[],
 *     keywords: string[],
 *     executiveSummary: string,
 *     slotLabel?: string,   // optional, set by the cron route
 *     isEmpty?: boolean     // set by cron when no fresh articles
 *   }
 *
 * Uses SMTP_* env vars + nodemailer to send through AWS SES (or any SMTP host).
 */

import nodemailer from 'nodemailer';
import { NextRequest, NextResponse } from 'next/server';
import type { Article } from '@/lib/types';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
export const maxDuration = 60;

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function highlightKeywords(text: string, keywords: string[]): string {
  let out = escapeHtml(text);
  for (const k of keywords) {
    if (!k) continue;
    const re = new RegExp(`\\b(${k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})\\b`, 'gi');
    out = out.replace(re, '<mark style="background:#FFF4D6;padding:0 2px;">$1</mark>');
  }
  return out;
}

function buildHtml(opts: {
  company: string;
  executiveSummary: string;
  articles: Article[];
  keywords: string[];
  slotLabel?: string;
  isEmpty?: boolean;
}): string {
  const dateStr = new Date().toLocaleString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });

  const emptyBanner = opts.isEmpty
    ? `<div style="padding:16px;background:#FAF7F2;border-left:4px solid #C9A961;
         margin-bottom:24px;font-family:Georgia,serif;color:#0A2540;">
         <strong>No significant news in the last 72 hours.</strong><br/>
         This is your scheduled briefing — keeping you in the loop even on quiet days.
       </div>`
    : '';

  const articleBlocks = opts.articles
    .slice(0, 30)
    .map((a) => {
      const ageBadge =
        a.undated ? `<span style="font-size:11px;color:#6B7280;background:#F4EFE6;padding:2px 6px;border-radius:3px;margin-left:6px;">undated</span>`
        : a.ageHours != null && a.ageHours < 24
          ? `<span style="font-size:11px;color:#0F7B5F;background:#E7F4EE;padding:2px 6px;border-radius:3px;margin-left:6px;">${Math.round(a.ageHours)}h ago</span>`
          : '';
      const sourceBadge = `<span style="font-size:11px;color:#0A2540;background:#E5DFD3;padding:2px 6px;border-radius:3px;">${escapeHtml(a.source)}</span>`;
      return `
        <tr><td style="padding:16px 0;border-bottom:1px solid #E5DFD3;">
          <div style="margin-bottom:6px;">${sourceBadge}${ageBadge}</div>
          <a href="${escapeHtml(a.link)}" style="font-family:Georgia,serif;font-size:17px;color:#0A2540;font-weight:600;text-decoration:none;">
            ${highlightKeywords(a.title, opts.keywords)}
          </a>
          ${a.whyPicked ? `<div style="font-family:Georgia,serif;font-size:14px;color:#1A1A1A;margin-top:8px;line-height:1.5;">${escapeHtml(a.whyPicked)}</div>` : ''}
          ${a.snippet ? `<div style="font-family:Georgia,serif;font-size:13px;color:#6B7280;margin-top:6px;line-height:1.45;">${highlightKeywords(a.snippet.slice(0, 240), opts.keywords)}…</div>` : ''}
        </td></tr>
      `;
    }).join('');

  return `<!doctype html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#FAF7F2;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#FAF7F2;padding:24px 0;">
    <tr><td align="center">
      <table role="presentation" width="640" cellpadding="0" cellspacing="0"
        style="background:#FFFFFF;border:1px solid #E5DFD3;border-radius:6px;padding:36px;max-width:640px;">
        <tr><td>
          <div style="font-family:Georgia,serif;font-size:13px;color:#6B7280;letter-spacing:1px;text-transform:uppercase;margin-bottom:6px;">
            PR Monitor · ${escapeHtml(opts.slotLabel ?? '')}
          </div>
          <h1 style="font-family:Georgia,serif;font-size:28px;color:#0A2540;margin:0 0 4px 0;">${escapeHtml(opts.company)} — Daily Brief</h1>
          <div style="font-family:Georgia,serif;font-size:14px;color:#6B7280;margin-bottom:24px;">${dateStr}</div>
          ${emptyBanner}
          <div style="font-family:Georgia,serif;font-size:15px;color:#1A1A1A;line-height:1.6;padding:16px;background:#FAF7F2;border-left:3px solid #C9A961;margin-bottom:24px;">
            ${escapeHtml(opts.executiveSummary)}
          </div>
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
            ${articleBlocks}
          </table>
          <div style="font-family:Georgia,serif;font-size:12px;color:#6B7280;margin-top:32px;padding-top:16px;border-top:1px solid #E5DFD3;">
            Generated by PR Monitor Agent · ${opts.articles.length} article${opts.articles.length === 1 ? '' : 's'} · last 72 hours
          </div>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;
}

export async function POST(req: NextRequest) {
  let body: {
    to?: string; cc?: string; company?: string;
    articles?: Article[]; keywords?: string[];
    executiveSummary?: string; slotLabel?: string; isEmpty?: boolean;
  };
  try { body = await req.json(); } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  if (!body.to || !body.company || !Array.isArray(body.articles)) {
    return NextResponse.json({ error: 'to, company, articles required' }, { status: 400 });
  }

  const host = process.env.SMTP_HOST;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  const from = process.env.SMTP_FROM ?? user;
  const port = Number(process.env.SMTP_PORT ?? 587);
  if (!host || !user || !pass || !from) {
    return NextResponse.json({ error: 'SMTP_* env vars not configured' }, { status: 500 });
  }

  const transport = nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    auth: { user, pass },
  });

  const html = buildHtml({
    company: body.company,
    executiveSummary: body.executiveSummary ?? '',
    articles: body.articles,
    keywords: body.keywords ?? [],
    slotLabel: body.slotLabel,
    isEmpty: body.isEmpty,
  });

  try {
    const info = await transport.sendMail({
      from,
      to: body.to,
      cc: body.cc,
      subject: `${body.company} — Daily PR Brief · ${new Date().toLocaleDateString('en-US')}`,
      html,
    });
    return NextResponse.json({ ok: true, messageId: info.messageId });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'send failed' },
      { status: 500 },
    );
  }
}
